- name: Install & Build
        run: |
          echo "--- 當前所在目錄 ---"
          pwd
          echo "--- 根目錄檔案清單 ---"
          ls -F
          # 先註釋掉原本會報錯的指令
          # npm install --legacy-peer-deps
